# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/xilinx_projects/16_ov5640_single/ov5640_single.srcs/sources_1/bd/system/ip/system_auto_us_4/system_auto_us_4.xci
# IP: The module: 'system_auto_us_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_projects/16_ov5640_single/ov5640_single.srcs/sources_1/bd/system/ip/system_auto_us_4/system_auto_us_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_us_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_projects/16_ov5640_single/ov5640_single.srcs/sources_1/bd/system/ip/system_auto_us_4/system_auto_us_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_us_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/xilinx_projects/16_ov5640_single/ov5640_single.srcs/sources_1/bd/system/ip/system_auto_us_4/system_auto_us_4.xci
# IP: The module: 'system_auto_us_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/xilinx_projects/16_ov5640_single/ov5640_single.srcs/sources_1/bd/system/ip/system_auto_us_4/system_auto_us_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_us_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/xilinx_projects/16_ov5640_single/ov5640_single.srcs/sources_1/bd/system/ip/system_auto_us_4/system_auto_us_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_us_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
