// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module p_hls_fptosi_double_s (
        ap_ready,
        x,
        ap_return
);


output   ap_ready;
input  [63:0] x;
output  [7:0] ap_return;

wire   [63:0] p_Val2_s_fu_44_p1;
wire   [51:0] tmp_V_1_fu_66_p1;
wire   [53:0] mantissa_V_fu_70_p4;
wire   [10:0] tmp_V_fu_56_p4;
wire   [11:0] tmp_i_i_i_cast1_fu_84_p1;
wire   [11:0] sh_assign_fu_88_p2;
wire   [10:0] tmp_i_i_fu_102_p2;
wire   [0:0] isNeg_fu_94_p3;
wire  signed [11:0] tmp_i_i_cast_fu_108_p1;
wire   [11:0] ush_fu_112_p3;
wire  signed [31:0] sh_assign_2_cast_fu_120_p1;
wire   [53:0] tmp_i_i_cast_49_fu_128_p1;
wire   [112:0] mantissa_V_1_cast_fu_80_p1;
wire   [112:0] tmp_i_i_48_fu_124_p1;
wire   [53:0] r_V_fu_132_p2;
wire   [0:0] tmp_fu_144_p3;
wire   [112:0] r_V_1_fu_138_p2;
wire   [7:0] tmp_2_fu_152_p1;
wire   [7:0] tmp_3_fu_156_p4;
wire   [7:0] p_Val2_5_fu_166_p3;
wire   [0:0] p_Result_s_fu_48_p3;
wire   [7:0] result_V_1_fu_174_p2;

assign ap_ready = 1'b1;

assign ap_return = ((p_Result_s_fu_48_p3[0:0] === 1'b1) ? result_V_1_fu_174_p2 : p_Val2_5_fu_166_p3);

assign isNeg_fu_94_p3 = sh_assign_fu_88_p2[32'd11];

assign mantissa_V_1_cast_fu_80_p1 = mantissa_V_fu_70_p4;

assign mantissa_V_fu_70_p4 = {{{{1'd1}, {tmp_V_1_fu_66_p1}}}, {1'd0}};

assign p_Result_s_fu_48_p3 = p_Val2_s_fu_44_p1[32'd63];

assign p_Val2_5_fu_166_p3 = ((isNeg_fu_94_p3[0:0] === 1'b1) ? tmp_2_fu_152_p1 : tmp_3_fu_156_p4);

assign p_Val2_s_fu_44_p1 = x;

assign r_V_1_fu_138_p2 = mantissa_V_1_cast_fu_80_p1 << tmp_i_i_48_fu_124_p1;

assign r_V_fu_132_p2 = mantissa_V_fu_70_p4 >> tmp_i_i_cast_49_fu_128_p1;

assign result_V_1_fu_174_p2 = (8'd0 - p_Val2_5_fu_166_p3);

assign sh_assign_2_cast_fu_120_p1 = $signed(ush_fu_112_p3);

assign sh_assign_fu_88_p2 = ($signed(12'd3073) + $signed(tmp_i_i_i_cast1_fu_84_p1));

assign tmp_2_fu_152_p1 = tmp_fu_144_p3;

assign tmp_3_fu_156_p4 = {{r_V_1_fu_138_p2[60:53]}};

assign tmp_V_1_fu_66_p1 = p_Val2_s_fu_44_p1[51:0];

assign tmp_V_fu_56_p4 = {{p_Val2_s_fu_44_p1[62:52]}};

assign tmp_fu_144_p3 = r_V_fu_132_p2[32'd53];

assign tmp_i_i_48_fu_124_p1 = $unsigned(sh_assign_2_cast_fu_120_p1);

assign tmp_i_i_cast_49_fu_128_p1 = $unsigned(sh_assign_2_cast_fu_120_p1);

assign tmp_i_i_cast_fu_108_p1 = $signed(tmp_i_i_fu_102_p2);

assign tmp_i_i_fu_102_p2 = (11'd1023 - tmp_V_fu_56_p4);

assign tmp_i_i_i_cast1_fu_84_p1 = tmp_V_fu_56_p4;

assign ush_fu_112_p3 = ((isNeg_fu_94_p3[0:0] === 1'b1) ? tmp_i_i_cast_fu_108_p1 : sh_assign_fu_88_p2);

endmodule //p_hls_fptosi_double_s
